---
title: Encoded art
hero_image: images/banner.png
description: Create a piece of encoded artwork based on the user's name.
meta_title: Python coding projects for kids and teens | Encoded art
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Use Python to create a piece of encoded art based on the user’s name.
version: 4
listed: true
copyedit: true
last_tested: "2021-11-03"
steps:
  - 
    title: You will make
  - 
    title: Choose a theme
  - 
    title: Draw your shapes
    completion:
      - engaged
  - 
    title: Place your shapes
  - 
    title: Build your dictionary
  - 
    title: Encode a message
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
  - 
    title: Share
  - 
    title: What next?
